Merge `develop` into `feature-web-proto` (#5526)
* Move FAQ to GitHub Discussions (#5412)

* Move FAQ to GitHub Discussions

* Fixed broken link

* Fixed broken link

* Update axis orientation in wrl (#5420)

* Copy icon when editing cached remote PROTO (#5414)

* Copy icon when editing web PROTO

* Fix cppcheck error

* Fix Windows nightly builds (#5439)

* Improvements on CMake template (#5421)

* Improvements on CMake template

Fixed a linking issue that may appear in some examples (I found it in the the crazyflie) in the CMake template.
The issue was a missing link to libm (set (LIBRARIES m...). It will show the following linking error: undefined reference to symbol 'fmax@@glibc_2.2.5'
Also added the WEBOTS_HOME variable in the CMake, just to avoid the hassle of having to export it in the console every time.

* Update docs/guide/using-your-ide.md

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Update docs/guide/using-your-ide.md

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Improved error message from empty animation (#5448)

* Stop pending animation on close (#5447)

* Stop pending animation on close 

If an animation recording is started and Webots is closed before it is stopped, the json animation file is not created. This adds a small check to stop the animation correctly when Webots is closed by the user in the GUI, with ctrl-C in the console or by a supervisor.

* Fixed trailing spaces

* Update WbAnimationRecorder.cpp

Co-authored-by: ad-daniel <44834743+ad-daniel@users.noreply.github.com>

* Improve robot window robustness to concatenated messages (#5442)

* Split concatenated messages before processing them

* Add changelog entry

* Update resources/web/wwi/RobotWindow.js

Co-authored-by: Benjamin Délèze <benjamin.deleze@cyberbotics.com>

* Update resources/web/wwi/RobotWindow.js

Co-authored-by: Benjamin Délèze <benjamin.deleze@cyberbotics.com>

* Update resources/web/wwi/RobotWindow.js

Co-authored-by: Benjamin Délèze <benjamin.deleze@cyberbotics.com>

Co-authored-by: Benjamin Délèze <benjamin.deleze@cyberbotics.com>

* Fix header required for PROTO files (#5453)

* require header for PROTO files

* Update changelog-r2023.md

* Documentation update for R2023a (#5450)

* Update thumbnails

* Update world by removing incorrect protos

Co-authored-by: ad-daniel <44834743+ad-daniel@users.noreply.github.com>

* Fix crash double `root to base node` (#5460)

* Inform that rows are about to be deleted

* Select item after conversion

* Update changelog-r2023.md

* Fix suggested project path (#5461)

* Fixed compilation on macOS (#5289)

* Fixed compilation, echo output on macOS

* Fixed echo -e

* Set JAVA_HOME automatically

* remove codesign from Makefile.include

* Update Makefile

* Update Makefile

* Compiles fixes for arm64

* Fixed compilation on arm64

* Update changelog-r2022.md

* Update changelog-r2022.md

* Got rid of aseba

* Removed aseba dependency

* Removed aseba documentation

* removed python brew

* Fixed mac distro on arm64

Co-authored-by: Yannick Goumaz <61198661+ygoumaz@users.noreply.github.com>

* Fixed missing exported function for Visual C++ (#5471)

* Added info regarding the name tag (#5459)

* Added info regarding the name tag

Added info regarding the default name tag in Accelerometer.md

* Code formatting

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Code formatting 2

* redaction improvement

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* added github_tree url to reference .wrl node file

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Fix crash when deleting some node and being connected to webotsJS (#5457)

* fix crash on delete

* Update changelog-r2023.md

* update translations (#5474)

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Better error message to help debugging the problem (#5482)

* Fixed tmp path on macOS (#5484)

* Fix tmp path on mac os (#5486)

* Fixed tmp path on macOS

* Fixed tmp dir also for extern controllers on macOS

* Fix external force/torque instructions (#5483)

* Fix instructions

* update translations

* Clarify

* Undo

* Update translations

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* remove path normalization + replace optparse (#5487)

* remove path normalization + replace optparse

* keep normpath for non-empty directories

* Update doc specifying that we should not free (#5494)

some returned string.

Co-authored-by: Yann LEROY <yann.leroy@manurob.com>

* Fixed Python API Node.resetPhysics (#5500)

* Improve extern controller name (#5498)

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Fix line feed character (#5495)

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>

* Fix motor sound on macOS (#5488)

* Fixed motor sounds on macOS

* Better code

* Update changelog-r2023.md

Co-authored-by: Stefania Pedrazzi <stefaniapedrazzi@users.noreply.github.com>

* Fix gtao shader in webotsJS (#5504)

* fix gtao

* Update src/wren/PostProcessingEffect.cpp

Co-authored-by: Yannick Goumaz <61198661+ygoumaz@users.noreply.github.com>

Co-authored-by: Yannick Goumaz <61198661+ygoumaz@users.noreply.github.com>

* Add `isInitializationPossible` to Python API (#5508)

* rename func + add to python

* keep old name

Co-authored-by: ad-daniel <44834743+ad-daniel@users.noreply.github.com>

* Removed obsolete Java controller warning for non-ASCII path (#5512)

* Improve the position of the viewpoint in the create.wbt (#5511)

Co-authored-by: ad-daniel <44834743+ad-daniel@users.noreply.github.com>

* Fix dialog popup opening/closing (#5513)

* Debug

* Fix

* Cleanup

* Better solution

* Fix test suite (#5505)

* Fix test suite

* Update test_suite_supervisor.py

* Sanity check, add bug

* Update WbLightSensor.cpp

* Add missing methods in Python API (#5516)

* add missing methods in supervisor and driver

* global api + remove useless methods

* Fix firstRender uniform type (#5517)

* Cleanup after innosetup install (#5520)

Co-authored-by: Olivier Michel <Olivier.Michel@cyberbotics.com>
Co-authored-by: Benjamin Délèze <benjamin.deleze@cyberbotics.com>
Co-authored-by: Stefania Pedrazzi <stefaniapedrazzi@users.noreply.github.com>
Co-authored-by: Toshiharu Tabuchi <rttf06@gmail.com>
Co-authored-by: Jean-Eudes-le-retour <62928319+Jean-Eudes-le-retour@users.noreply.github.com>
Co-authored-by: Yannick Goumaz <61198661+ygoumaz@users.noreply.github.com>
Co-authored-by: ShuffleWire <83014015+ShuffleWire@users.noreply.github.com>
Co-authored-by: Yann LEROY <yann.leroy@manurob.com>